---

- name: create sudoers.d file
  file:
    path: "/etc/sudoers.d/{{ username }}"
    owner: root
    group: root
    mode: 0740
    state: touch

- name: configure to give a permission to user
  lineinfile:
    dest: "/etc/sudoers.d/{{ username }}"
    line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
    state: present
