---

# include vault environment variables
- include_vars:
    file: "roles/secret/vault/{{ _environment }}.yml"

# include environment variables
- include_vars:
    file: "roles/secret/vars/{{ _environment }}.yml"

- name: install GoRead secret key
  template: 
    src: "roles/secret/templates/goread_secret_key" 
    dest: "/etc/goread_secret_key"
    owner: goread
    group: goread
    mode: 0440

- name: link iba_secret_key
  file:
    src: '/etc/goread_secret_key'
    dest: '/etc/iba_secret_key'
    state: link
    owner: goread
    group: goread
    mode: 0440
