---

- name: Install ImageMagick for tests related to images
  apt: 
    name: imagemagick
    state: present
  when: 
    - ansible_distribution == "Ubuntu"

- name: Download PhantomJS
  get_url:
    url: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    dest: /tmp/phantomjs.tar.bz2
    checksum: md5:1c947d57fce2f21ce0b43fe2ed7cd361
  when:
    - ansible_distribution == "Ubuntu"

- name: Install PhantomJS
  shell: tar xf /tmp/phantomjs.tar.bz2 -C /usr/local/bin --strip-components=2 phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  when:
    - ansible_distribution == "Ubuntu"

- name: PhantomJS Cleanup
  shell: rm -r /tmp/phantomjs.tar.bz2
  when:
    - ansible_distribution == "Ubuntu"
